API_TOKEN = 'random-bits-go-here'  # your api key as generated by slack goes here
BOT_NAME = 'edibot'  # name of your bot in slack so it can notify you there, otherwise goes to slackbot
PLUGINS = [
    'slackhub'
]
